version: "3.8"

services:
  langchain_server:
    container_name: langchain_server
    build:
      context: .
      dockerfile: ./backend/langchain_app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #command: tail -f /dev/null
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pandasai_server:
    container_name: pandasai_server
    build:
      context: .
      dockerfile: backend/pandasai_app/Dockerfile
    command: uvicorn backend.pandasai_app.main:app --host 0.0.0.0 --port 9000
    expose:
      - 9000
    ports:
      - 9000:9000
    env_file: ".env"

  streamlit_frontend:
    container_name: streamlit_frontend
    build:
      context: ./frontend
    command: "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    volumes:
      - ./frontend/app:/code
    expose:
      - 8501
    ports:
      - 8501:8501
    env_file: ".env"

