version: "3.8"

services:
  fastapi_server:
    container_name: ${PROJECT_NAME}_fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker langchain_agent.main:langchain_agent  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/langchain_agent:/code
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file: ".env"

  streamlit_frontend:
    container_name: ${PROJECT_NAME}_streamlit_frontend
    build: ./frontend
    restart: always
    volumes:
      - ./frontend/langchain_agent:/code
    expose:
      - 8501

    env_file: ".env"

volumes:
  caddy_data:
  caddy_config:
